FLIP-2183: Sort graphs on FLIP UI
AI4VBH/FLIP-ui pull request #31
Opened 2023-03-16 10:07 UTC by MichaelOSullivanAnswer

Below are snapshots of the charts now including all possible x-axis values in the one data set and sorting correctly:
![Screenshot 2023-03-16 095534](https://user-images.githubusercontent.com/116073025/225584018-06fd026c-11e1-43bf-8ecd-e0070031fae2.jpg)
![Screenshot 2023-03-16 095626](https://user-images.githubusercontent.com/116073025/225584039-594c254f-71af-4e8c-af79-0ad814617d65.jpg)

2023-03-16 10:22 UTC, handyandypandyandy commented
Great stuff! For the metrics graphs, could you try and make it so the individual global rounds are shown or at least represented in a way where the ticks in-between make a bit more sense. For example, between global rounds 3 and 6 there are four minor ticks which doesn't make much sense as global rounds will always be integers, there can't be 3.75 global rounds. You should be able to modify some additional settings in the x axis to control how the ticks represented.

2023-03-16 10:35 UTC, carlsmith-ad requested changes
Would we be able to update the x-axis label for the Model Metrics to be 'Global Rounds', as its not clear what this value represents

2023-03-20 10:43 UTC, MichaelOSullivanAnswer commented
<img width="379" alt="image" src="https://user-images.githubusercontent.com/116073025/226317043-a5166f9f-87ac-49ec-9c54-22cad84120aa.png">

2023-03-20 11:03 UTC, handyandypandyandy commented on src/components/AiChart/AiCohortChart.vue
> +
empty space here is inconsistent with the map function below

2023-03-20 11:15 UTC, MichaelOSullivanAnswer commented on src/components/AiChart/AiCohortChart.vue
> +        const xAxisValues = [...new Set(([] as string[]).concat(...xAxisData))].sort();
xAxisData will be the array that is passed is as the data for the x-axis, so needs to contain only unique values from the cohort query. xAxisData will have an array for each trust, so while we only have the two trusts as of now I was looking for a way to deal with any number of trusts. The '[...new Set()]' is the syntax for creating a new set so that we only have unique values. So you are basically unpacking the arrays in xAxisData and adding unique values to xAxisValues.

2023-03-20 11:22 UTC, handyandypandyandy commented on src/components/AiChart/AiCohortChart.vue
> +        const xAxisValues = [...new Set(([] as string[]).concat(...xAxisData))].sort();
spot on about using Set() that will easily get rid of duped values but also you should be able to pass in an array to initialise it. No need to use a casted empty array or concatenating data on the end

2023-03-20 12:08 UTC, MichaelOSullivanAnswer commented on src/components/AiChart/AiCohortChart.vue
> +        const xAxisValues = [...new Set(([] as string[]).concat(...xAxisData))].sort();
great I thought there had to be a cleaner way of doing this I couldn't seem to get it working in the one go at the time, thanks. This has been updated

2023-03-20 12:13 UTC, MichaelOSullivanAnswer commented on src/components/AiChart/AiCohortChart.vue
> +
this variable has been removed

2023-03-20 12:51 UTC, handyandypandyandy approved these changes

2023-03-21 09:00 UTC, carlsmith-ad approved these changes

2023-03-21 09:45 UTC, merged